//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Disable_AudioNonUSB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tool_Disable_AudioNonUSB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Disable_Audio {
            get {
                object obj = ResourceManager.GetObject("Disable_Audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Enable_Audio {
            get {
                object obj = ResourceManager.GetObject("Enable_Audio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///1. Bật/Tắt Secure Boot:
        ///   - Khởi động lại máy và vào BIOS bằng F2/F10/F12/DEL.
        ///   - Tìm mục Secure Boot (trong Security/Boot/Advanced).
        ///   - Bật: Chọn Enabled.
        ///   - Tắt: Chọn Disabled.
        ///   - Lưu và thoát (F10 &gt; Yes).
        ///
        ///2. Bật/Tắt TPM:
        ///   - Khởi động lại máy và vào BIOS.
        ///   - Tìm mục TPM (hoặc PTT/fTPM trong Security).
        ///   - Bật: Chọn Enabled.
        ///   - Tắt: Chọn Disabled hoặc Clear TPM.
        ///   - Lưu và thoát (F10 &gt; Yes).
        ///
        ///3. Bật/Tắt HVCI:
        ///   - Khởi động lại máy và vào BIOS.
        ///   - Tìm các mục Virtual [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Max_Volume {
            get {
                object obj = ResourceManager.GetObject("Max_Volume", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maxresdefault {
            get {
                object obj = ResourceManager.GetObject("maxresdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
